# This is the configuration used to check the rubocop source code.

# inherit_from: .rubocop_todo.yml
require: rubocop/cop/internal_affairs

AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'
    - 'db/schema.rb'
    - 'config/routes.rb'
    - 'config/deploy.rb'
    - 'node_modules/**/*'
    - 'bin/**/*'
  DisplayCopNames: true


# Bundler/DuplicatedGem:
#   Enabled: false

Layout/EndOfLine:
  EnforcedStyle: lf

Layout/IndentHeredoc:
  EnforcedStyle: powerpack

Layout/TrailingWhitespace:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*.rb'

Lint/InterpolationCheck:
  Exclude:
    - 'spec/**/*.rb'

# Lint/ScriptPermission:
#   Enabled: true

Lint/HandleExceptions:
  Enabled: false

Lint/UselessAccessModifier:
  MethodCreatingMethods:
    - 'def_matcher'
    - 'def_node_matcher'

Lint/BooleanSymbol:
  Enabled: false

Metrics/AbcSize:
  Max: 35

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'

Metrics/LineLength:
  Max: 200

Metrics/MethodLength:
  Max: 45

Metrics/ModuleLength:
  Exclude:
    - 'spec/**/*.rb'

Performance/Caller:
  Exclude:
    - spec/rubocop/cop/performance/caller_spec.rb

Style/AsciiComments:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false
  EnforcedStyle: compact

Style/Copyright:
  Enabled: false

Style/Documentation:
  Enabled: false  

Style/DocumentationMethod:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/IdenticalConditionalBranches:
  Enabled: false

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Style/NumericPredicate:
  EnforcedStyle: comparison

Style/PercentLiteralDelimiters:
  Enabled: false

Style/RegexpLiteral:
  EnforcedStyle: mixed
  Enabled: false
  
Style/SymbolArray:
  EnforcedStyle: brackets
