default: &default
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: dudintv
  password: qwerty
  host: localhost

development:
  <<: *default
  database: toster_development

test:
  <<: *default
  database: toster_test

# production:
#   <<: *default
#   database: toster_production
#   username: dudintv
#   password: <%= ENV['TOSTER_DATABASE_PASSWORD'] %>
