# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 61c19bf8bfb90a27ae1d0c6c7610fcf9fdbc57688c01f74be6d693cf13163a5e0f94191f9125e43372d612755f2127161b7683d977c5e2cc4983b9a88d4338d0
  facebook_app_id: 160258781242634
  facebook_app_secret: c40cd53cfc644eb7da6332d803955ccc
  twitter_app_id: n95UdXdrUogZhv1YtgtITCnjL
  twitter_app_secret: D3Nj7pTsbIVS7XTtPAtYUhwTYTWnQMgpFTuDTuODyHsO5moayy
  vkontakte_app_id: 6287192
  vkontakte_app_secret: V9MiuxI8fM5Xkx0k25L1

test:
  secret_key_base: e217aca505c46fc79f068658bd18b67fb355941c245a1f8d59c4cc331d75ae691b16892d84f8a7b42457a671ba34a5e6a24cac281f82c20ea511e18d5adadcea

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  facebook_app_id: <%= ENV["FACEBOOK_APP_ID"] %>
  facebook_app_secret: <%= ENV["FACEBOOK_APP_SECRET"] %>
