test:
  mysql41: 9307
production:
  mysql41: 3306
  user: root
  pid_file: /home/deploy/toster/shared/tmp/searchd.pid
  indices_location: /home/deploy/toster/shared/db/sphinx
  configuration_file: /home/deploy/toster/shared/production.sphinx.conf
  binlog_path: /home/deploy/toster/shared/binlog